/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cgsuite.help;

import java.awt.BorderLayout;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javax.help.JHelp;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.cgsuite.help//CgsuiteHelp//EN",
autostore = false)
@TopComponent.Description(preferredID = "CgsuiteHelpTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "help", openAtStartup = false)
@ActionID(category = "Window", id = "org.cgsuite.help.CgsuiteHelpTopComponent")
@ActionReference(path = "Menu/Window", position = 1750)
@TopComponent.OpenActionRegistration(displayName = "#CTL_CgsuiteHelpAction",
preferredID = "CgsuiteHelpTopComponent")
public final class CgsuiteHelpTopComponent extends TopComponent {

    private JHelp helpViewer;

    public CgsuiteHelpTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CgsuiteHelpTopComponent.class, "CTL_CgsuiteHelpTopComponent"));
        setToolTipText(NbBundle.getMessage(CgsuiteHelpTopComponent.class, "HINT_CgsuiteHelpTopComponent"));
        final JFXPanel fxPanel = new JFXPanel();
        add(fxPanel, BorderLayout.CENTER);
        Platform.setImplicitExit(false);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                WebView webView = new WebView();
                webView.getEngine().setUserStyleSheetLocation(HelpBuilder.class.getResource("docs/cgsuite.css").toExternalForm());
                webView.getEngine().load(getClass().getResource("docs/game/CanonicalShortGame.html").toExternalForm());
                fxPanel.setScene(new Scene(webView));
            }
        });

        //JEditorPane pane = new JEditorPane();
        //HTMLEditorKit kit = new HTMLEditorKit();
        //NbEditorKit kit = new NbEditorKit();
        //NbEditorDocument doc = new NbEditorDocument("text/html");
        //kit.getStyleSheet().importStyleSheet(getClass().getResource("docs/cgsuite.css"));
        //pane.setEditorKit(kit);
        //pane.setDocument(doc);
        /*try {
            pane.setContentType("text/html");
            pane.setPage(getClass().getResource("docs/game/CanonicalShortGame.html"));
        } catch (IOException exc) {
            throw new RuntimeException(exc);
        }
            ((HTMLDocument) pane.getDocument()).getStyleSheet().importStyleSheet(getClass().getResource("docs/cgsuite.css"));
        add(pane, BorderLayout.CENTER);*/
        /*
        HelpSet help = Lookup.getDefault().lookup(HelpSet.class);
        helpViewer = new JHelp(help);
        Enumeration e = helpViewer.getHelpNavigators();
        while (e.hasMoreElements())
        {
            JHelpNavigator navigator = (JHelpNavigator) e.nextElement();
            if (navigator instanceof JHelpIndexNavigator)
            {
                helpViewer.removeHelpNavigator(navigator);
                break;
            }
        }
        */
        //add(helpViewer, BorderLayout.CENTER);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }
    
    public JHelp getHelpViewer()
    {
        return helpViewer;
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
}
