/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cgsuite.ui.explorer;

import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.cgsuite.ui.explorer//Explorer2//EN",
autostore = false)
@TopComponent.Description(preferredID = "Explorer2TopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "org.cgsuite.ui.explorer.Explorer2TopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_Explorer2Action",
preferredID = "Explorer2TopComponent")
public final class Explorer2TopComponent extends TopComponent {

    public Explorer2TopComponent() {
        initComponents();
        setName(NbBundle.getMessage(Explorer2TopComponent.class, "CTL_Explorer2TopComponent"));
        setToolTipText(NbBundle.getMessage(Explorer2TopComponent.class, "HINT_Explorer2TopComponent"));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primarySplitPane = new javax.swing.JSplitPane();
        detailSplitPane = new javax.swing.JSplitPane();
        editorScrollPane = new javax.swing.JScrollPane();
        analysisPanel = new javax.swing.JPanel();
        worksheetScrollPane = new javax.swing.JScrollPane();
        commandPanel = new javax.swing.JPanel();
        inputPanel = new org.cgsuite.ui.worksheet.InputPanel();
        commandTextArea = new javax.swing.JTextArea();
        treeScrollPane = new javax.swing.JScrollPane();
        treePanel = new org.cgsuite.ui.explorer.ExplorerTreePanel();
        infoPanel = new javax.swing.JPanel();
        addPositionButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        primarySplitPane.setBackground(new java.awt.Color(255, 255, 255));
        primarySplitPane.setDividerLocation(480);

        detailSplitPane.setBackground(new java.awt.Color(255, 255, 255));
        detailSplitPane.setDividerLocation(480);
        detailSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        detailSplitPane.setTopComponent(editorScrollPane);

        analysisPanel.setBackground(new java.awt.Color(255, 255, 255));
        analysisPanel.setLayout(new java.awt.BorderLayout());
        analysisPanel.add(worksheetScrollPane, java.awt.BorderLayout.CENTER);

        commandPanel.setBackground(new java.awt.Color(255, 255, 255));
        commandPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        commandPanel.setLayout(new javax.swing.BoxLayout(commandPanel, javax.swing.BoxLayout.Y_AXIS));

        inputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 0, 4));
        commandPanel.add(inputPanel);

        commandTextArea.setColumns(20);
        commandTextArea.setEditable(false);
        commandTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        commandTextArea.setRows(5);
        commandTextArea.setAlignmentX(0.0F);
        commandTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 2, 4));
        commandPanel.add(commandTextArea);

        analysisPanel.add(commandPanel, java.awt.BorderLayout.NORTH);

        detailSplitPane.setRightComponent(analysisPanel);

        primarySplitPane.setLeftComponent(detailSplitPane);

        treeScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        treeScrollPane.setViewportView(treePanel);

        primarySplitPane.setRightComponent(treeScrollPane);

        add(primarySplitPane, java.awt.BorderLayout.CENTER);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(addPositionButton, org.openide.util.NbBundle.getMessage(Explorer2TopComponent.class, "Explorer2TopComponent.addPositionButton.text")); // NOI18N
        infoPanel.add(addPositionButton);

        typeLabel.setBackground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(typeLabel, org.openide.util.NbBundle.getMessage(Explorer2TopComponent.class, "Explorer2TopComponent.typeLabel.text")); // NOI18N
        typeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 4));
        infoPanel.add(typeLabel);

        add(infoPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPositionButton;
    private javax.swing.JPanel analysisPanel;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JTextArea commandTextArea;
    private javax.swing.JSplitPane detailSplitPane;
    private javax.swing.JScrollPane editorScrollPane;
    private javax.swing.JPanel infoPanel;
    private org.cgsuite.ui.worksheet.InputPanel inputPanel;
    private javax.swing.JSplitPane primarySplitPane;
    private org.cgsuite.ui.explorer.ExplorerTreePanel treePanel;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JScrollPane worksheetScrollPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
